print('Введите первое число:')
number_one = int(input())
print('Введите второе число:')
number_two = int(input())
print('Вводятся два числа:', number_one, 'и', number_two)
print('Результаты вычислений:')
print(number_one, 'умноженное на', number_two, 'равно', number_one * number_two)
print(number_one, 'деленное на', number_two, 'равно', number_one / number_two)
print(number_one, 'нацело деленное на', number_two, 'равно', number_one // number_two)
print('Остаток от деления', number_one, 'на', number_two, 'равно', number_one % number_two)
print(number_one, 'в степени', number_two, 'равно', number_one ** number_two)
